### PR TITLE
Mobile Responsive Footer

### PR DESCRIPTION
**Pull request by aannyyaa**

### CODE REVIEW

**Review by saifulislamdev — APPROVED** [review]

**Comment by saifulislamdev** [comment]
Try to think more about how you can potentially organize your `_class-overrides` code.

**Comment by saifulislamdev** [comment]
We might have discussed this already, but how come all the class overrides are in `_class-overrides`? Can we break it down into different files? It's currently ~600 lines.

**Comment by aannyyaa** [comment]
> We might have discussed this already, but how come all the class overrides are in `_class-overrides`? Can we break it down into different files? It's currently ~600 lines.

We did discuss in code review and said then it could stay in one file. Maybe it would make sense though to have a mixins file, general styles (links, buttons, etc) file, and media queries file?

**Comment by saifulislamdev** [comment]
> We did discuss in code review and said then it could stay in one file. Maybe it would make sense though to have a mixins file, general styles (links, buttons, etc) file, and media queries file?

I thought it could follow the structure we have for our components so that the styles match each component, and it would be easy to find. It's commonly done this way as well unless USWDS projects follow a certain format.

**Pull request merged**
